### ISSUE TITLE
Front page: when toolbar is open, then footer block is not in full size visible

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-madrid#13]
Can't edit footer, is not visible:
![screen shot 2015-11-18 at 16 38 55](https://cloud.githubusercontent.com/assets/13623224/11243875/43d79670-8e13-11e5-8030-5bf6766d4d19.png)

Footer block is visible:
![screen shot 2015-11-18 at 16 41 22](https://cloud.githubusercontent.com/assets/13623224/11243890/531400b0-8e13-11e5-9d37-eacec11ca870.png)

**Comment by kaspar-naaber** [comment]
Should be fixed.
