### ISSUE TITLE
Add design editor support

### ISSUE THREAD

**Issue by hennrunnel** [Voog/design-madrid#14]

**Comment by SSirjes** [comment]
* [ ]  Focus area alignment and position editing options are too close to each other

![arrows](https://cloud.githubusercontent.com/assets/13623224/14638341/a33e8ac0-063f-11e6-8ac3-e044e921a8d4.jpg)

**Comment by SSirjes** [comment]
* [ ]  Content header is not displayed in mobile. Tested in android, iPod
![screenshot_20160419-163633](https://cloud.githubusercontent.com/assets/13623224/14641187/b4eb57c2-064d-11e6-852a-93d619e952af.jpg)

**Comment by SSirjes** [comment]
* [ ] **Default article content area is wider than common page content area**
Video: http://recordit.co/xaCN2yz5n8

**Comment by SSirjes** [comment]
III round testing

* [ ] Blog article add comment text is connected with h2. Is this correct?
![screen shot 2016-04-27 at 08 23 01](https://cloud.githubusercontent.com/assets/13623224/14842642/fd03409c-0c51-11e6-8315-0aaaddb19af9.png)
