### ISSUE TITLE
Add ecommerce related layouts.

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-madrid#83]
PR: https://github.com/Voog/design-madrid/pull/84

---

Add 
* [x] product list layout
* [x] product layout

**Comment by siimha** [comment]
* [ ] menu-breadcrumbs have no hover

**Comment by siimha** [comment]
* [ ] If you set content text color to white then it also changes form field selector color & it's not visible any more.
![screen shot 2018-05-21 at 15 20 19 2](https://user-images.githubusercontent.com/35253483/40310409-50381bf0-5d15-11e8-916f-1ab4a0f57337.png)

**Comment by siimha** [comment]
* [ ] If submenu color is white then it is not visible in mobile view http://recordit.co/OPDHFwcLvC

**Comment by siimha** [comment]
* [ ] Text color in product list & product layout content area should mabye change from content text color? 
![screen shot 2018-05-21 at 15 49 50 2](https://user-images.githubusercontent.com/35253483/40310485-a4bcb0d2-5d15-11e8-9f49-582c278c35cb.png)

**Comment by siimha** [comment]
* [ ] If root_item layout is product list layout and you hide product & product list items from menu then it applies also to product layout when you change it to root_item. http://recordit.co/V7dVl5RX5K

FIX: Remove product layout from main menu hidden categories rendering
`{% for item in site.visible_menuitems %}`
{% if site.root_item.layout_title == product_list_layout ~~or site.root_item.layout_title == product_layout~~ %}
`{% if editmode %}
  {% include "menu-level-1-link" render_hidden_categories: true %}
  {% else %}`

Remove product layout from menu-level-1-link rendering if statement:
{% if render_hidden_categories == true and item.layout_title == product_list_layout ~~or item.layout_title == product_layout~~ %}
